act/act/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ranks.urls')),
]

act/ranks/urls.py
from django.urls import path
from . import views

app_name = 'ranks'
urlpatterns = [
    path('', views.home, name='home'),
    path('data', views.enterTeamData, name='data1'),
]

act/ranks/views.py
from abc import abstractproperty
from django.shortcuts import render, redirect
from .models import Player, ACT, GlobalVariables
import openpyxl, math

# Create your views here.

#OVERALL STAT SETUP
def home(request):
    #players = ["Eashan Panjwani","Zach Bell","Benner Mullin","Jackson Brodwolf","Matt Halper","Alex Hazel","Harris Klein","Kohl Terry","Alex Mellas","Noah Paige","Julian Ricci","Robbie Kramer","Ethan Roberts","Henry Rogers","Ryan Simon","Peter Netchvolodoff","Andrew Schanuel","Avery Friedman","Josh Greenfield","Will Spartin","Will Goldberg","Brady Sheaffer","Aman Patil","Zach Stern","Josh Josef","Nico Simon", "Sam Schoepke", "James Berthoud","Jonathan Nurko", "Spencer Gladstone","Kion Noori", "Max Marchetto", "Chuck Leonetti", "Matt Flower", "Connor Caz", "Caleb Hughes", "Lukas Steinbock","Brian Volk"]
    player_dict = {}
    players = Player.objects.order_by('-elo')
    print("TEST")
    for player_object in players:
        print("uyay")
        if player_object.acts_ran > -1:
            player_dict[player_object.name] = player_object
        resetCounter = False
        if resetCounter == True:
            if (player_object.name == "Andrew Schanny" or player_object.name == "James Berthoud" or player_object.name == "Brian Volk" or player_object.name == "Josh Greenfield" or player_object.name == "Ethan Roberts" or player_object.name == "Will Spartin" or player_object.name == "Matt Halper"):
                player_object.elo = 1500
            elif (player_object.league == "A-League"):
                player_object.elo = 2000
            elif (player_object.league == "C-League"):
                player_object.elo = 1500
            else:
                player_object.elo = 1000
            player_object.acts_ran = 0
            player_object.elo_change = 0
            player_object.elo_change1 = 0
            player_object.elo_change2 = 0
            player_object.elo_change3 = 0
            player_object.elo_change4 = 0
            player_object.elo_change5 = 0
            player_object.total_points = 0
            player_object.accum_competitor_elo = 0
            player_object.save()
    return render(request, "ranks/home.html", {'dict': player_dict})

"""

def race(request):
    player_dict = {}
    players = Player.objects.order_by('-race rating') #add variable for race rating into player model
    for player_object in players:
        player_dict[player_object.name] = player_object
    return render(request, "ranks/race.html", {'dict': player_dict})

def player(request):
    race_dict = {}
    races = Race.objects
    for race_object in races:
        race_dict[race_object.name] = race_object
    return render(request, "ranks/player.html")

"""

#INDIVIDUAL ACT STAT SETUP
def enterTeamData(request):
    if "GET" == request.method:
        return render(request, 'ranks/teamData.html', {})
    else:
        excel_file = request.FILES["excel_file"]
        # you may put validations here to check extension or file size
        wb = openpyxl.load_workbook(excel_file)
        # getting a particular sheet by name out of many sheets
        worksheet = wb.active
        print(worksheet)
        excel_data = list()
        # iterating over the rows and
        # getting value from each cell in row
        rowCount = 1
        team1player1 = 0
        team1player2 = 0
        team2player1 = 0
        team2player2 = 0
        team3player1 = 0
        team3player2 = 0
        team4player1 = 0
        team4player2 = 0
        team1player1name = ""
        team1player2name = ""
        team2player1name = ""
        team2player2name = ""
        team3player1name = ""
        team3player2name = ""
        team4player1name = ""
        team4player2name = ""
        team1character1name = ""
        team1character2name = ""
        team2character1name = ""
        team2character2name = ""
        team3character1name = ""
        team3character2name = ""
        team4character1name = ""
        team4character2name = ""

        player_dict = {
            "EP" : "Eashan Panjwani",
            "AS" : "Andrew Schanny",
            "PN" : "Peter Netch",
            "ZB" : "Zach Bell",
            "BM" : "Benner Mullin",
            "JB" : "Jackson Brodwolf",
            "MH" : "Matt Halper",
            "AH" : "Alex Hazel",
            "HK" : "Harris Klein",
            "KT" : "Kohl Terry",
            "AM" : "Alex Mellas",
            "NP" : "Noah Paige",
            "JR" : "Julian Ricci",
            "RK" : "Robbie Kramer",
            "ER" : "Ethan Roberts",
            "HR" : "Henry Rogers",
            "RS" : "Ryan Simon",
            "AF" : "Avery Friedman",
            "JG" : "Josh Greenfield",
            "WS" : "Will Spartin",
            "WG" : "Will Goldberg",
            "BS" : "Brady Sheaffer",
            "AP" : "Aman Patil",
            "ZS" : "Zach Stern",
            "NS" : "Nico Simon",
            "JJ" : "Josh Josef",
            "SS" : "Sam Schoepke",
            "TJ" : "James Berthoud",
            "JN" : "Jonathan Nurko",
            "SG" : "Spencer Gladstone",
            "KN" : "Kion Noori",
            "MM" : "Max Marchetto",
            "CL" : "Chuck Leonetti",
            "MF" : "Matt Flower",
            "CC" : "Connor Caz",
            "CH" : "Caleb Hughes",
            "LS" : "Lukas Steinbock",
            "BV" : "Brian Volk",
            "NSh" : "Nitan Shalon",
            "MZ" : "Mat Zlotnick",
            "GM" : "Gavin Morse"
        }

        act_object = ACT()
        t1player1_score = ""
        t1player2_score = ""
        t2player1_score = ""
        t2player2_score = ""
        t3player1_score = ""
        t3player2_score = ""
        t4player1_score = ""
        t4player2_score = ""

#READING EXCEL SHEET TO GET PLAYER POINTS
        for row in worksheet.iter_rows():
            if rowCount > 32:
                break
            if rowCount == 1 or rowCount == 2 or rowCount == 9 or rowCount == 10 or rowCount == 11 or rowCount == 12 or rowCount == 17 or rowCount == 18 or rowCount == 19 or rowCount == 20 or rowCount == 25 or rowCount == 26 or rowCount == 27 or rowCount == 28:
                rowCount+= 1
                continue
            rowCount+= 1
            row_data = list()
            cellCount = 1
            for cell in row:
                if cellCount == 1:
                    cellCount +=1 
                    continue
                row_data.append(str(cell.value))
                if rowCount == 4:
                    if cellCount == 3:
                        team1player1name = player_dict[str(cell.value)]
                    if cellCount == 4:
                        team1player2name = player_dict[str(cell.value)]
                    if cellCount == 5:
                        team2player1name = player_dict[str(cell.value)]
                    if cellCount == 6:
                        team2player2name = player_dict[str(cell.value)]
                    if cellCount == 7:
                        team3player1name = player_dict[str(cell.value)]
                    if cellCount == 8:
                        team3player2name = player_dict[str(cell.value)]
                    if cellCount == 9:
                        team4player1name = player_dict[str(cell.value)]
                    if cellCount == 10:
                        team4player2name = player_dict[str(cell.value)]
                if rowCount == 5:
                    if cellCount == 3:
                        team1character1name = str(cell.value)
                    if cellCount == 4:
                        team1character2name = str(cell.value)
                    if cellCount == 5:
                        team2character1name = str(cell.value)
                    if cellCount == 6:
                        team2character2name = str(cell.value)
                    if cellCount == 7:
                        team3character1name = str(cell.value)
                    if cellCount == 8:
                        team3character2name = str(cell.value)
                    if cellCount == 9:
                        team4character1name = str(cell.value)
                    if cellCount == 10:
                        team4character2name = str(cell.value)
                if rowCount != 4 and rowCount != 5:
                    if cellCount == 3: 
                        if cell.value != None:
                            team1player1 += int(cell.value)
                            t1player1_score += str(cell.value)
                        else:
                            t1player1_score += "null"
                        t1player1_score += ","
                    if cellCount == 4: 
                        if cell.value != None:
                            team1player2 += int(cell.value)
                            t1player2_score += str(cell.value)
                        else:
                            t1player2_score += "null"
                        t1player2_score += ","
                    if cellCount == 5: 
                        if cell.value != None:
                            team2player1 += int(cell.value)
                            t2player1_score += str(cell.value)
                        else:
                            t2player1_score += "null"
                        t2player1_score += ","
                    if cellCount == 6: 
                        if cell.value != None:
                            team2player2 += int(cell.value)
                            t2player2_score += str(cell.value)
                        else:
                            t2player2_score += "null"
                        t2player2_score += ","
                    if cellCount == 7: 
                        if cell.value != None:
                            team3player1 += int(cell.value)
                            t3player1_score += str(cell.value)
                        else:
                            t3player1_score += "null"
                        t3player1_score += ","

act/ranks/templates/ranks/actList.html
<!DOCTYPE html>
{% load mathfilters %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>
    {%if dict%}
        <table>
          <tr class="tableheader">
            <th class="heading">ACT ID</th>
            <th class="heading">League</th>
            <th class="heading">Delete</th>
          </tr>
      {%for act_id, league in dict.items%}
            <tr>
              <th>{{act_id}}</th>
              {%if league == "A-League"%}
                <th><font color="cyan">{{league}}</font></th>
              {%elif league == "C-League"%}
                <th><font color="yellow">{{league}}</font></th>
              {%else%}
                <th><font color="lightgreen">{{league}}</font></th>
              {%endif%}
            </tr>
        {%endfor%}
        </table>
      {%endif%}
  </body>
  <style>

    table, th {
      border-collapse: collapse;
    }
    table{
      width: 100%;
      color: white;
    }
    .heading{
      font-size: 25px;
      text-align: center;
      font-weight: bold;
    }
    body {
      background-color: rgb(41, 41, 41);
    }
    tr{
      line-height: 30px;
    }
    tr:nth-child(even) {
      background-color: rgb(71, 71, 71)
    }
    tr:nth-child(odd) {
      background-color: rgb(100, 100, 100)
    }
  </style>
</html>

act/ranks/templates/ranks/home.html
<!DOCTYPE html>
{% load mathfilters %}
<html>
  <head>
    <meta charset="utf-8">
    <title>ACT Ranks Fall 2021</title>
  </head>
  <body>
    {%if dict%}
        <table>
          <tr class="tableheader">
            <th class="heading">Position</th>
            <th class="heading">Name</th>
            <th class="heading">League</th>
            <th class="heading">Elo Rating</th>
            <th class="heading">Change in Elo (from last 5 ACTs)</th>
            <th class="heading">Average Competitor Elo</th>
            <th class="heading">ACTs Ran</th>
            <th class="heading">Avg. Points</th>
          </tr>
      {%for name, player in dict.items%}
            <tr>
              <th>{{forloop.counter}}</th>
              <th>{{name}}</th>
              {%if player.league == "A-League"%}
                <th><font color="cyan">{{player.league}}</font></th>
              {%elif player.league == "C-League"%}
                <th><font color="yellow">{{player.league}}</font></th>
              {%else%}
                <th><font color="lightgreen">{{player.league}}</font></th>
              {%endif%}
              <th>{{player.elo}}</th>
              {%if player.elo_change > 0%}
                <th><font color="lightgreen">{{player.elo_change}}</font></th>
              {%elif player.elo_change < 0 %}
                <th><font color="pink">{{player.elo_change}}</font></th>
              {%else%}
                <th>{{player.elo_change}}</th>
              {%endif%}
              {%if player.acts_ran != 0%}
                <th>{{player.accum_competitor_elo|div:player.acts_ran|floatformat:0}}</th>
              {%else%}
                <th>N/A</th>
              {%endif%}
              <th>{{player.acts_ran}}</th>
              {%if player.acts_ran != 0%}
              <th>{{player.total_points|div:player.acts_ran|floatformat:2}}</th>
              {%else%}
              <th>N/A</th>
              {%endif%}
            </tr>
        {%endfor%}
        </table>
      {%endif%}
  </body>
  <style>

    table, th {
      border-collapse: collapse;
    }
    table{
      width: 100%;
      color: white;
    }
    .heading{
      font-size: 25px;
      text-align: center;
      font-weight: bold;
    }
    body {
      background-color: rgb(41, 41, 41);
    }
    tr{
      line-height: 30px;
    }
    tr:nth-child(even) {
      background-color: rgb(71, 71, 71)
    }
    tr:nth-child(odd) {
      background-color: rgb(100, 100, 100)
    }
  </style>
</html>

act/ranks/templates/ranks/player.html
<!DOCTYPE html>
{% load mathfilters %} <!UNEDITED****** from race.html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>
    {%if dict%}
        <table>
          <tr>
            <th>Position</th>
            <th>Name</th>
            <th>Race Rating</th>
            <th>1st</th>
            <th>2nd</th>
            <th>3rd</th>
            <th>4th</th>
          <tr>
      {%for name, player in dict.items%}
          <tr>
            <th>{{forloop.counter}}</th>
            <th>{{name}}</th>
            <th>{{player.race rating}}</th> <!whatever the variable is in player model>
            <th>{{player.number 1sts}}</th> <!whatever the variable is in player model>
            <th>{{player.number 2nds}}</th> <!whatever the variable is in player model>
            <th>{{player.number 3rds}}</th> <!whatever the variable is in player model>
            <th>{{player.number 4ths}}</th> <!whatever the variable is in player model>
          <tr>
          {%endfor%}
        </table>
      {%endif%}
  </body>
</html>

act/ranks/templates/ranks/race.html
<!DOCTYPE html>
{% load mathfilters %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>
    {%if dict%}
        <table>
          <tr>
            <th>Position</th>
            <th>Name</th>
            <th>Race Rating</th>
            <th>1st</th>
            <th>2nd</th>
            <th>3rd</th>
            <th>4th</th>
          <tr>
      {%for name, player in dict.items%}
          <tr>
            <th>{{forloop.counter}}</th>
            <th>{{name}}</th>
            <th>{{player.race rating}}</th> <!whatever the variable is in player model>
            <th>{{player.number 1sts}}</th> <!whatever the variable is in player model>
            <th>{{player.number 2nds}}</th> <!whatever the variable is in player model>
            <th>{{player.number 3rds}}</th> <!whatever the variable is in player model>
            <th>{{player.number 4ths}}</th> <!whatever the variable is in player model>
          <tr>
          {%endfor%}
        </table>
      {%endif%}
  </body>
</html>

act/ranks/templates/ranks/raceData.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>
    <p>Insert Race Data</p>
    <hr>
    {% if error%}
        <p> {{error}} </p>
    {% endif %}
    {% csrf_token %}
    <br>
    {{raceform}}
    <input type="submit" value="Submit">
    <br> 
    <br>
  </body>
</html>

act/ranks/templates/ranks/teamData.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <p class="datitle">Create ACT Teams</p>
    <hr>
    {% if error%}
        <p> {{error}} </p>
    {% endif %}
    {% csrf_token %}

    <form action="{% url "ranks:data1" %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file"
             title="Upload excel file"
             name="excel_file"
             style="border: 1px solid black; padding: 5px;"
             required="required">
      <p>
      <input type="submit"
             value="Upload"
             style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
  </form>

  <p></p>
  <hr>

  {% for row in excel_data %}
      {% for cell in row %}
          {{ cell }}&nbsp;&nbsp;
      {% endfor %}
      <br>
  {% endfor %}
    <br>
    <table>
    <!--
    <form method="get">
      <input type="submit" value="Submit">
    </form> -->
  </table>
    <br> 
    <br>
  <style>
    .datitle{
      margin-left: 10px;
      font-weight: bold;
    }
    .blockLabel {
      font-weight: bold;
      margin-left: 10px;
    }
    .ctrlHolder {
    display:inline;
    margin-left: 50px;
  }
    .ctrlHolder:after {
    content:"\a";
    white-space: pre;
}
  </style>
  </body>
</html>